name = "aiken-lang/aiken-linked-list"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/aiken-linked-list'"

[repository]
user = "aiken-lang"
project = "aiken-linked-list"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
